#%RAML 1.0
title: WDK Rest Service
version: 3.0
baseUri: //{siteUrl}/{webApp}/service

/:
  get:
    description: Get basic information about the WDK service.
    responses:
      200:
        description: success response
        body:
          application/json:
            type: !include ../../src/main/resources/schema/wdk/get-response.json
            example: !include ./includes/example/get-service-200.json

/answer: !include ./includes/raml/answer-api.raml

/api: !include ./includes/raml/api-api.raml

/client-errors: !include ./includes/raml/client-errors-api.raml

# /cpu-test:
#   get:
#     description: ???
#     queryParameters:
#       numTrials:
#         type: integer
#         format: int64
#     responses:
#       200:
#         description: Success
#         body:
#           text/plain:

/login:
  displayName: Login
  get:
  post:
    body:
      application/json:
  /verification:
    get:

/logout:
  displayName: Logout
  get:
    description: Logs the current user out and adds them to a guest session.

/oauth: !include ./includes/raml/oauth-api.raml
/ontologies: !include ./includes/raml/ontologies-api.raml
/record-types: !include ./includes/raml/record-types-api.raml
/record-types/{record-type}/searches: !include ./includes/raml/searches-api.raml
/record-types/{record-type}/searches/{search-name}/reports: !include ./includes/raml/reports-api.raml

/strategy: !include ./includes/raml/strategy-api.raml
/strategy-list: !include ./includes/raml/strategy-list-api.raml
/system: !include ./includes/raml/system-api.raml

# /teapot:
#   get:
#     responses:
#       418:
#         description: I am a teapot

/temporary-results: !include ./includes/raml/temporary-results-api.raml

/upload:

/user-id-query:
  displayName: User ID Query
  post:
    description: |
      Accepts an array of email addresses and attempts to locate the user ids
      (if any) associated with them.  Retuns an array of objects containing a
      single email as a key mapped to the matching user id.

      If an email address is not in the system, it will be excluded from the
      output list.
    body:
      application/json:
        type: !include ../../src/main/resources/schema/wdk/user-id-query/post-request.json
        example: !include ./includes/example/post-user-id-query-input.json
    responses:
      200:
        body:
          application/json:
            type: !include ../../src/main/resources/schema/wdk/user-id-query/post-response.json
            example: !include ./includes/example/post-user-id-query-200.json

/user-password-reset:
  displayName: User Password Reset
  post:
    description: Reset a user's password.
    body:
      application/json:
        type: !include ../../src/main/resources/schema/wdk/user-password-reset/post-request.json
        example: !include ./includes/example/post-user-password-reset-input.json
    responses:
      204:

/user-datasets/config:
  displayName: User Dataset Config
  get:
    responses:
      200:
        description: Success
        body:
          application/json:
            example: !include ./includes/example/get-user-datasets-config-200.json

/users: !include ./includes/raml/users-api.raml

/users/steps: !include ./includes/raml/users/steps-api.raml

/users/steps/{stepId}/analyses: !include ./includes/raml/users/step-analyses-api.raml

/users/steps/{stepId}/analysis-types: !include ./includes/raml/users/step-analysis-types-api.raml
