export let APP_LOADING = 'APP_LOADING';
export let APP_ERROR = 'APP_ERROR';

// FIXME These should be past-tense
export let ANSWER_LOADING = 'ANSWER_LOADING';
export let ANSWER_ADDED = 'ANSWER_ADDED';
export let ANSWER_MOVE_COLUMN = 'ANSWER_MOVE_COLUMN';
export let ANSWER_CHANGE_ATTRIBUTES = 'ANSWER_CHANGE_ATTRIBUTES';
export let ANSWER_UPDATE_FILTER = 'ANSWER_UPDATE_FILTER';

export let QUESTIONS_ADDED = 'QUESTIONS_ADDED';

export let RECORD_CLASSES_ADDED = 'RECORD_CLASSES_ADDED';

export let RECORD_DETAILS_ADDED = 'RECORD_DETAILS_ADDED';
export let RECORD_CATEGORY_COLLAPSED_TOGGLED = 'RECORD_CATEGORY_COLLAPSED_TOGGLED';
export let RECORD_TABLE_COLLAPSED_TOGGLED = 'RECORD_TABLE_COLLAPSED_TOGGLED';

export let PREFERENCES_LOADED = 'PREFERENCES_LOADED';
export let PREFERENCE_SET = 'PREFERENCE_SET';
export let PREFERENCE_REMOVED = 'PREFERENCE_REMOVED';
export let PREFERENCE_REMOVED_ALL = 'PREFERENCE_REMOVED_ALL';
