/**
 * 
 */
package org.gusdb.wdk.model.test;

import java.util.HashMap;

import org.gusdb.wdk.model.WdkModel;
import org.gusdb.wdk.model.WdkModelException;
import org.gusdb.wdk.model.WdkUserException;
import org.gusdb.wdk.model.user.User;
import org.gusdb.wdk.model.user.UserFactory;

import junit.framework.TestCase;

/**
 * @author xingao
 * 
 */
public class UserFactoryTest extends TestCase {

    UserFactory factory;

    public static void main(String[] args) {
        junit.textui.TestRunner.run(UserFactoryTest.class);
    }

    /*
     * @see TestCase#setUp()
     */
    protected void setUp() throws Exception {
        super.setUp();
        // load WdkModel
        TestUtility utility = TestUtility.getInstance();
        WdkModel model = utility.getWdkModel();
        factory = model.getUserFactory();
    }

    /*
     * Test method for 'org.gusdb.wdk.model.user.UserFactory.sendEmail(String,
     * String, String, String)'
     */
    public void testSendEmail() {
        try {
            factory.sendEmail("jerric@pcbi.upenn.edu", "jerric@uga.edu",
                    "UserFactory Unit Test",
                    "Here is a test email generated by the UserFactoryTest automatically.");
        } catch (WdkUserException ex) {
            // TODO Auto-generated catch block
            ex.printStackTrace();
        }
    }

    /*
     * Test method for 'org.gusdb.wdk.model.user.UserFactory.createUser(String,
     * String, String, String, String, String, String, String, String, String,
     * String, String, String)'
     */
    public void testCreateUser() {
        try {
            User user = factory.createUser("jerric@uga.edu", "Gao", "Jerric",
                    "", "Mr.", "UGA", "Biology", "C210 Life Science", "Athens",
                    "GA", "36302", "706-542-1447", "USA",
                    new HashMap<String, String>(),
                    new HashMap<String, String>());
            assertNotNull(user);
            assertFalse(user.isGuest());
        } catch (WdkUserException ex) {
            ex.printStackTrace();
            assertTrue(false);
        }
    }

    /*
     * Test method for 'org.gusdb.wdk.model.user.UserFactory.createGuestUser()'
     */
    public void testCreateGuestUser() {
        User user = factory.getGuestUser();
        assertNotNull(user);
        assertTrue(user.isGuest());
    }

    /*
     * Test method for
     * 'org.gusdb.wdk.model.user.UserFactory.authenticate(String, String)'
     */
    public void testAuthenticate() {
        try {
            User user = factory.authenticate("jerric@uga.edu", "jerric");
            assertNotNull(user);
            assertFalse(user.isGuest());
        } catch (WdkUserException ex) {
            ex.printStackTrace();
            assertTrue(false);
        }
    }

    /*
     * Test method for 'org.gusdb.wdk.model.user.UserFactory.saveUser(User)'
     */
    public void testSaveUser() {
        try {
            User user = factory.authenticate("jerric@uga.edu", "jerric");
            assertNotNull(user);
            assertFalse(user.isGuest());

            // update user information, and save it
            user.setAddress("524 Guardian dr. 1428 Blockley Hall");
            user.setCity("Philadelphia");
            user.setDepartment("Center for Bioinformatics");
            user.setOrganization("University of Pennsylvania");
            user.addUserRole("administrator");
            factory.saveUser(user);
        } catch (WdkUserException ex) {
            ex.printStackTrace();
            assertTrue(false);
        }
    }

    /*
     * Test method for 'org.gusdb.wdk.model.user.UserFactory.loadHistory(User)'
     */
    public void testLoadHistory() {

    }

    /*
     * Test method for
     * 'org.gusdb.wdk.model.user.UserFactory.saveHistories(User)'
     */
    public void testSaveHistories() {

    }

    /*
     * Test method for
     * 'org.gusdb.wdk.model.user.UserFactory.deleteHistory(String, int)'
     */
    public void testDeleteHistory() {

    }
}
