package org.gusdb.wdk.model.record;

import java.util.List;
import java.util.Map;

import org.gusdb.wdk.model.answer.AnswerValue;

public interface ResultProperties {
	
	Map getPropertyValues(AnswerValue answerValue);
	
	/**
	 * used to validate that the property values generated by the implementation confirm to those declared in the xml model
	 * @param propNames
	 */
	void setPropertyNames(List<String> propNames);

}
