# User Basket API
#
# This RAML doc is a draft.  The details below are pulled from the google doc
# do not necessarily reflect the actual implementation.
#
# @path /users/{id}/baskets

# Methods
get:
  description: Get a list of the user's baskets.  Returns a JSON object mapping basket name to the number of records in that basket.  For now only one basket is supported per record-type, for those record-types that allow baskets.  All allowed baskets, including empty ones, are returned in this listing.
  responses:
    200:
      description: Success
      body:
        application/json:
          type: !include ../../../../schema/wdk/users/baskets/get-response.json

# Child Endpoints
/{basketName}:
  get:
    description: Returns detailed information for the basket of the specified name.

  patch:
    description: >
      Add and/or remove records to/from this basket.
    responses:
      204:

  delete:
    description: > Removes all records from this basket.  The basket itself is not deleted.
      
    responses:
      204:
        description: No content

  /query:
    post:
      description: >
        For the list of records provided in the body, discover which are in this basket.

  /reports/standard:
    post:
      description: Runs a report on the records in this basket.  See the /reports endpoint under /searches.

  /reports/{reportName}
    post:
      description: Runs a report on the records in this basket.  See the /reports endpoint under /searches.
