# Users Favorites API
	  
get:
  description: Returns array of user's favorites (takes rc param to filter)
  responses:
    200:
      description: Success
      body:
        application/json:
          type: !include ../../../../../src/main/resources/schema/wdk/users/favorites/get-response.json

patch:
  description: Accepts instructions for editing/deleting multiple favorites
  body:
    application/json:
      type: !include ../../../../../src/main/resources/schema/wdk/users/favorites/patch-request.json
  responses:
    200:
      description: Success
      body:
        application/json:
          type: !include ../../../../../src/main/resources/schema/wdk/users/favorites/patch-response.json

post:
  description: >
    Adds the passed favorite (object) or favorites (array) to user's favorites
    and returns with IDs

/{favoriteId}:
  uriParameters:
    favoriteId:
      description: user favorite id
      type: integer

  get:
    description: Returns the specified favorite
    responses:
      200:
        description: Success
        body:
          application/json:
            type: !include ../../../../../src/main/resources/schema/wdk/users/favorites/get-response.json

  patch:
    description: Replaces the specified favorite with the passed one
    body:
      application/json:
        type: !include ../../../../../src/main/resources/schema/wdk/users/favorites/id/put-request.json
    responses:
      204:
        description: No content

  delete:
    description: Deletes the specified favorite
    responses:
      204:
        description: No content

/query:
  post:
    description: >
      Takes array of {record-type + primary keys} objects as JSON and returns object containing the subset of those that are favorites.
