# User Preference API

description: Key value store

get:
  description: Object of user preferences
  responses:
    200:
      body:
        application/json:
          type: !include ../../../../../src/main/resources/schema/wdk/users/preferences/get-response.json
patch:
  description: >
    Update preferences passed (missing prefs are unaffected)
put:
  description: >
    Replace all user preferences with those passed in (delete missing prefs)

/record/{class}:
  get:
    description: "TBD: the user's configuration of this record class"
    uriParameters:
      class:
        type: string

  /sections:
    description: TBD: configuration of the sections for this record class
