get:
  description: Get names, display names, and icons of available tools.
  responses:
    200:
      body:
        application/json:
          type: !include ../../../../schema/wdk/users/steps/analysis-types/get-response.json

/{analysis-type-name}:
  uriParameters:
    analysis-type-name:
      type: string
  get:
    description: >
      Get (possibly dynamic) form creation information + default
      values.
    responses:
      200:
        body:
          application/json: