# Users Steps API

post:
  description: |
    * Creates a new search strategy step.  A Step is always created unattached to a strategy.  (Use the strategy/ endpoint to add the step to a strategy.  At that point, the step will be assigned its strategy ID.)
    * If the associated search does not have step parameters all parameters are validated.
    * If the associated search does have step parameters:
        * In the request body, step parameter values must be set to an empty string, else validation will fail. (Step parameters are exclusively handled by /strategy)
        * The other parameters will be validated as usual.
    * If validation of any param fails, no step is created and a 400/500 HTTP response will be returned
  body:
    application/json:
      type: !include ../../../../schema/wdk/users/steps/post-request.json
  responses:
    200:
      description: Success
      body:
        application/json:
          type: !include ../../../../schema/wdk/standard-post-response.json

/{step-id}:
  uriParameters:
    step-id:
      type: integer
      format: int64

  get:
    description: |
      * Returns full JSON of the step, including all parameter values.
          * This is to support the revise-a-search form (to fill in initial values) and any display of the step's search configuration.
	  * The following are only validated when the step is run, so are not guaranteed to be valid at the time of this GET:
              * steps provided in step parameters are owned by the requester
              * datasets provided in dataset parameters are owned by the requester
    responses:
      200:
        description: Success
        body:
          application/json:
            type: !include ../../../../schema/wdk/users/steps/id/get-response.json

  patch:
    description: |
      * Used to modify the step (but not its searchConfig or placement within its strategy)
      * The only modifiable fields are:
          * customName
          * isCollapsible
          * collapsedName
	  * displayPrefs
    body:
      application/json:
        type: !include ../../../../schema/wdk/users/steps/id/patch-request.json
    responses:
      204:
        description: No Content

  delete:
    description: Delete the step.  Only allowed for steps that are not yet attached to a strategy.  Otherwise use the strategy/ service.
    responses:
      204:
        description: No Content

  /reports/standard:
    post:
      description: |
        GET by POST.  Get the result of this step as a report. 
        * Input JSON is the same as the "reportConfig" property in searches/{searchName}/reports/standard requests
            * If the body is empty, defaults are used
        * Step status fields (estimatedSize, isValid, lastRunTime) are updated
        * If the step has no strategy ID (i.e. is not yet part of a strategy) the request will fail.
      body:
        application/json:
	  type: !include ../../../../schema/wdk/includes/answer-formatConfig-json-request.json
      responses:
        200:
          description: Success

  /reports/{reportName}:
    post:
      description: |
        GET by POST.  Get the result of this step as a report. 
        * Use the GET step/{stepId}/reports endpoint to get a listing of available reports and their request details (NOT IMPLEMENTED YET).
        * Step status fields (estimatedSize, isValid, lastRunTime) are updated
        * If the step has one or more step parameters but no strategy ID (i.e. is not yet part of a strategy) the request will fail.
      body:
        application/json:
	  type: !include ../../../../schema/wdk/includes/answer-formatConfig-json-request.json
      responses:
        200:
          description: Success

  /search-config:
    put:
      description: |
        update the searchConfig of a step (but do not re-run the step)
          * Any part of the searchConfig may be changed (to revise the step), except step parameter values, which will cause validation failure
          * The new searchConfig is validated
              * if validation fails, 400/500 response is returned and step is not updated
              * If validation passes:
                * estimatedSize is cleared for this and, if this step is part of a strategy, all downstream steps
      body:
        application/json:
	  type: !include ../../../../schema/wdk/answer/answer-spec-request.json
      responses:
        204:
          description: No Content

  /reports/filter-summary/{filterName}:
    uriParameters:
      name:
        type: string
    get:
      description: >
        return data needed to display a filter's UI
      responses:
        200:
          description: Success



