# User Strategy API

description: TBD
get:
  responses:
    200:
      body:
        application/json:
          type: array
          items:
            type: object
            properties:
              strategyId:
                type: integer
                format: int64
              description:
                type: string
              name:
                type: string
              author:
                type: string
              latestStepId:
                type: string
              recordClassName:
                type: string
              signature:
                type: string
              lastModified:
                type: string
              isPublic:
                type: boolean
              isSaved:
                type: boolean
              isValid:
                type: boolean
              isDeleted:
                type: boolean
              organization:
                type: string
              estimatedSize:
                type: integer
post:
  responses:
    200:
      body:
        application/json:
          type: object
          properties:
            id:
              type: integer
              format: int64


/{class}:
  uriParameters:
    class:
      type: string
  get:
    description: >
      TBD: a multi-column listing of the user's strategies of this record type
      TBD: filter this set of strategies, by, eg, open, closed, saved, unsaved
      filter by a hand-selected set
    queryParameters:
      filter:
      filterlist:

/{strategy-id}:
  get:
    responses:
      200:
        body:
          application/json:
  patch:
    description: TBD open, close
