require('./views/core/view');
require('./views/core/collapsible_view');
require('./views/core/question_view');
require('./views/core/tabs_view');
require('./views/core/template_view');
// require('./views/filter/field_list_view');
// require('./views/filter/range_filter_view');
// require('./views/filter/membership_filter_view');
// require('./views/filter/field_detail_view');
// require('./views/filter/filter_fields_view');
// require('./views/filter/results_view');
// require('./views/filter/filter_item_view');
// require('./views/filter/filter_items_view');
require('./views/strategy/step_box_view');
require('./views/strategy/step_detail_view');
require('./views/strategy/strategy_view');
