displayName: Question

get:
  description: questions
  queryParameters:
    recordClass:
      description: if provided, limit to that record class
      type: string
    expandQuestions:
      description: if true, then provide details of questions
      type: boolean
    expandParams:
      description: if true, then provide details of params
      type: boolean

/{questionName}:
  uriParameters:
    questionName:
      type: string
  get:
    description: >
      Get info for building a question form, including all vocabularies (except
      filter params and type ahead params).  For dependent params, if `stepId`
      provided, this is a step revise;  use the step to get depended param
      values.  Otherwise, use defaults.
    queryParameters:
      stepId:
        type: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../../../../src/main/resources/schema/wdk/questions/get-response.json
            example: !include ../example/get-questions-200.json

  post:

  /refreshed-dependent-params:
    post:

  /{paramName}:
    uriParameters:
      paramName:
        type: string
    get:
      description: >
        Get a get parameter's details, including vocab if appropriate.
        For dependent params, if `stepId` provided, this is a step revise;  use
        the step to get depended param values.  Otherwise, use defaults.
        Client will need to call this to get filter params and enum params with
        displayType="typeAhead".
      queryParameters:
        stepId:
        displayType:
    post:
      description: >
        GET by POST.  Get a dependent parameter's details, including vocab.. The
        body must contain a JSON map of depended param values. (These will be
        validated).  Because of complexity of dependent parameters' relationship,
        the client must guarantee these calls are ordered correctly.

    /ontology-term-summary:
      post:
    /summary-counts:
      post:
    /internal-value:
      post:

