displayName: Strategy List

get:
  description: summary info about a set of strategies
  queryParameters:
    ids:
      description: idList
    action:
      description: open, close, delete

/public:
  get:
    description: a multi-column list of public strategies
