displayName: Strategy

/{strategy-id}:
  uriParameters: 
    strategy-id: 
      type: integer
  delete:
    description: delete
  get:
    description: summary info about a strategy
  patch:
    description: rename, saveAs, makePublic

  /details:
    get:
      description: detailed info about a strategy (like step count)

  /duplicate:
    get:
      description: the ID of a newly created duplicate of this strategy

  /record/{class}:
    uriParameters: 
      class: 
        type: string
    /column/{name}:
      uriParameters: 
        name: 
          type: string
      delete:
        description: delete column
      put:
        description: add column

  /share:
    get:
      description: an URL to share this strategy

  /steps:
    get:
      description: get the step tree
    patch:
      description: >
        revise the step tree (insert before, insert after, delete step) (server
        does validation)
