displayName: System

/appdb/connections:
  get:
    description:  Administrative access required for this function.  Unclosed connection info for the app database.
    responses: 
      403:
        description: Unauthorized
        body: 
          text/plain:
            type: string

/caches:
  get:
    description:  Administrative access required for this function.  Usage stats for various in memory data stores.
    responses: 
      200:
        description: Success
        body: 
          application/json:
	  
/userdb/connections:
  get:domain
    description: Administrative access required for this function.  Unclosed connection information for the user database.  
    responses: 
      403:
        description: Unauthorized
        body: 
          text/plain:
            type: string
