displayName: Temporary Files

post:
  description: Take the file stream from the request and write it to a temporary files directory on the server.  Return the generated temp file name in the header
  body:
    multipart/form-data:
  responses: 
    200:
      description: Success

