# Users API
#
# This RAML doc is a draft.  The details below are pulled from the google doc
# do not necessarily reflect the actual implementation.
#
# @path /users

displayName: User API


# Methods

get:
  description: list of all users (probably won’t implement)

post:
  description: >
    register a new, unverified user, and return input JSON (but now id is
    populated)


# Child Endpoints

/{user-id}: !include users/by-id.raml
