== Overview
* This describes the backend.  There is client.
* There is a REST service
* There is a WDK Model that:
** is created dynamically at startup, by reading a set of XML model configuration files
** describes the data and data processing that is available in this running instance of the WDK.
* There are subsystems.

== Records and Record Classes
* A _Record_ is the WDK's concept of a document. It is an instance of a Record Class.  
** It typically manifests in a website:
*** as a page displaying a single record
*** in contexts, such as search results, displaying a collection of record summaries.
** It provides information such as
*** multi-part primary key
*** attributes (single-valued properties)
*** tables (tabular-valued properties)
* A _Record Class_ defines the information available in instances of the record class.
** A record class is specified in one or more XML files that are part of the WDK model configuration.  The XML file provides:
*** An interface to this record class.  The interface is exposed to clients as a REST API for the record class
*** Implementation details on how to:
**** acquire data called for by the interface, and
**** process that data for display and peripheral analysis
** The specific types of information it provides are:
*** The display name for the type of this record, eg *Gene*
*** The url segment name for this type of record, to be used in the path of endpoints that refer to records.  Eg `gene`
*** A primary key definition.  
**** a reference to a data source (SQL query) that returns one or more row for every record of this type
***** this provides for:
****** a single source of truth for valid primary keys of this record type, used in validation contexts
****** a mapping of deprecated versions of a primary key for a given record to the current version of its primary key.
***** the columns returned are:
****** one each for the one or more parts of the primary key.  
****** parallel columns with the `_old` suffix.  
***** The rows returned include:
****** one row for each record in which the `_old` columns contain the "identity" mapping, ie, the "old" primary key is the same as the current one. (This ensures that there is always at least a one row per record, and allows the system to always look up a primary key by the `_old` columns.)
****** there may be additional rows for a record if it has deprecated primary keys, if there are any for a given record.

